In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('patient-medical-records-2024.xlsx')

In [3]:
df.columns

Index(['admissions.case_year', 'admissions.hash', 'admissions.id', 'exams.age',
       'exams.age_unit', 'exams.attitude', 'exams.bcs', 'exams.body',
       'exams.cardiopulmonary', 'exams.cns', 'exams.comments',
       'exams.dehydration', 'exams.examined_at', 'exams.examiner',
       'exams.forelimb', 'exams.gastrointestinal', 'exams.head',
       'exams.hindlimb', 'exams.integument', 'exams.mm_color',
       'exams.mm_texture', 'exams.musculoskeletal', 'exams.nutrition',
       'exams.sex', 'exams.temperature', 'exams.temperature_unit',
       'exams.treatment', 'exams.type', 'exams.weight', 'exams.weight_unit',
       'patient_locations.area', 'patient_locations.comments',
       'patient_locations.enclosure', 'patient_locations.moved_in_at',
       'patient_locations.where_holding', 'patients.address_found',
       'patients.admitted_at', 'patients.admitted_by', 'patients.band',
       'patients.carcass_saved', 'patients.care_by_rescuer',
       'patients.city_found', 'patients.clinical_signs',
       'patients.common_name', 'patients.county_found',
       'patients.criminal_activity', 'patients.custom_field_1',
       'patients.custom_field_2', 'patients.days_in_care',
       'patients.diagnosis', 'patients.disposition',
       'patients.disposition_county', 'patients.disposition_lat',
       'patients.disposition_lng', 'patients.disposition_location',
       'patients.disposition_subdivision', 'patients.dispositioned_at',
       'patients.dispositioned_by', 'patients.found_at', 'patients.keywords',
       'patients.lat_found', 'patients.lng_found', 'patients.microchip_number',
       'patients.morph', 'patients.name', 'patients.notes_about_rescue',
       'patients.reason_for_disposition', 'patients.reasons_for_admission',
       'patients.reference_number', 'patients.release_type',
       'patients.subdivision_found', 'patients.transfer_type',
       'patients.transported_by', 'people.address', 'people.alt_phone',
       'people.city', 'people.country', 'people.county', 'people.email',
       'people.entity', 'people.first_name', 'people.is_member',
       'people.is_volunteer', 'people.last_name', 'people.no_solicitations',
       'people.notes', 'people.organization', 'people.phone',
       'people.postal_code', 'people.subdivision', 'species.class',
       'species.family', 'species.genus', 'species.order', 'species.species'],
      dtype='object')

## Drop Rows where there is no geolocation information

In [4]:
df[['patients.address_found', 'patients.county_found', 'patients.city_found']]

,patients.address_found,patients.county_found,patients.city_found
0,1179 SR-712,Loudoun,Upperville
1,3250 Bust Head Rd,Fauquier,The Plains
2,Intersection of Greenway and Rt 7,Loudoun,Leesburg
3,109 Keverne Ct.,Frederick,Stephens City
4,21024 Fox Hollow Ln.,Loudoun,Leesburg
...,...,...,...
3312,225 Sister Chipmunk Ln,Frederick,Clearbrook
3313,20333 Tanager Place,Loudoun,Leesburg
3314,Found on a walking trail behind Dockside Terra...,Fairfax,Sterling
3315,297 Cedar Mtn. Ln.,Warren,Front Royal
3316,4723 Benjamin Cross Ct.,Fairfax,Chantilly

Some of the data in 'patients.address_found' is not useful for programatically determining lat long coordinates. We want to drop the rows where the address_found starts with a alphabetic character AND either lat_found or lng_found is null

In [7]:
# determine which rows have the 'patients.address_found' column starting with a non-numeric character 
# df[df['patients.address_found'].str[0].str.isnumeric() == True]
# Set the 'patients.address_found' column to null for these rows
df.loc[df['patients.address_found'].str[0].str.isnumeric() == False, 'patients.address_found'] = None

In [8]:
# Drop rows where all the following columns are empty: 'patients.address_found', 'patients.lat_found', 'patients.long_found'
df = df.dropna(subset=['patients.address_found', 'patients.lat_found', 'patients.lng_found'], how='all')

## Convert Address to Geolocation
For rows where we have an address but no lat or long info

In [8]:
df[['patients.address_found', 'patients.lat_found', 'patients.lng_found']]

,patients.address_found,patients.lat_found,patients.lng_found
0,1179 SR-712,NaN,NaN
1,3250 Bust Head Rd,NaN,NaN
2,Intersection of Greenway and Rt 7,NaN,NaN
3,109 Keverne Ct.,NaN,NaN
4,21024 Fox Hollow Ln.,NaN,NaN
...,...,...,...
3312,225 Sister Chipmunk Ln,NaN,NaN
3313,20333 Tanager Place,NaN,NaN
3314,Found on a walking trail behind Dockside Terra...,39.040332,-77.354295
3315,297 Cedar Mtn. Ln.,NaN,NaN
3316,4723 Benjamin Cross Ct.,NaN,NaN

In [17]:
# Drop rows where either lat_found or _lng_found is NaN
df = df.dropna(subset=['patients.lat_found', 'patients.lng_found'])

In [ ]:
# Unchecked but general direction of code
import geopy
from geopy.geocoders import Nominatim

loc = Nominatim(user_agent="Geopy Library")
get_loc = loc.geocode(df['patients.address_found'])
print(get_loc.latitute, "\n")
print(get_loc.longitude)

In [ ]:
df[p[]]

In [21]:
df[['patients.lat_found', 'patients.lng_found']]

      patients.lat_found  patients.lng_found
48             38.831823       -7.752172e+01
75             39.034220       -7.740088e+01
174            39.501650       -7.801266e+01
183            38.841123       -7.792664e+07
186            39.039670       -7.791998e+07
...                  ...                 ...
3243           39.165549       -7.818914e+01
3265           39.030428       -7.750816e+01
3272           39.040514       -7.742277e+01
3300           39.086555       -7.813949e+01
3314           39.040332       -7.735429e+01

[122 rows x 2 columns]

## Determine Which ones are Vehicle Collision Related

* The patients.keyword column contains relevant information. Search for "HBV" (Hit by Vehicle).
* The patients.diagnosis column also has relevant data - "HBV" and "HBV" as a string in long from text
* the patient.reasons_for_admission column has relevent info: "HBV" among others

### Keyword Column

In [9]:
# Find all rows in the patient.keywords column that contain the string "HBV" and examine the results
df[df['patients.keywords'].str.contains('HBV', regex=False, case=False, na=False)]['patients.keywords'].value_counts()

patients.keywords
suspect HBV                                                152
B - Baby, mother killed, mother HBV, orphan                 20
B - Baby, orphan, mother HBV                                18
B - Baby, mother HBV, small                                  9
suspect HBV, mother killed, B - Baby, small                  8
B - Baby, suspect HBV                                        7
mother HBV, mother killed, orphan, B - Baby, small           6
B - Baby, small, mother HBV, orphan                          5
suspect HBV, B - Baby                                        4
suspect HBV, finder negligence                               2
trauma, suspect HBV                                          2
mother HBV, B - Baby, orphan                                 2
B - Baby, mother killed, mother HBV, orphan, dog attack      2
suspect HBV, lead                                            2
suspect HBV,  suspect cat attack                             1
suspect HBV, URI                                             1
B - Baby, mother HBV, mother killed, orphan                  1
gunshot, suspect HBV                                         1
suspect HBV, rabies suspect                                  1
B - Baby, mother killed, dog attack, mother HBV, orphan      1
HBV                                                          1
grounded, trauma, suspect HBV                                1
Name: count, dtype: int64

In [10]:
# Grab the indexes of the rows that contain the string "HBV" in the patient.keywords column
keyword_column_hbv = df[df['patients.keywords'].str.contains('HBV', regex=False, case=False, na=False)].index

### Diagnosis Column

In [11]:
df['patients.diagnosis'].value_counts()

patients.diagnosis
T - Unknown Trauma                       768
D - Domestic animal attack               440
B - Baby                                 411
S - Non-infectious Disease               243
H - Hit by Vehicle                       166
M - Human non-intentional                158
X - Invasive                             157
I - Infectious Disease                   123
A - Abduction                            119
W - Window Strike                         83
U - Unknown                               34
K - Toxicity                              25
P - Predator Attack                       22
F - Monofilament line or fishing hook     15
J - Intentional Human Attack               7
N - Natural Event                          5
D - Domestic animal attack, baby           1
Name: count, dtype: int64

In [12]:
# Find all rows in the patient.diagnosis column that are equal to "H - Hit by Vehicle" and examine the results
df[df['patients.diagnosis'].str.contains('Vehicle', regex=False, case=False, na=False)]['patients.diagnosis'].value_counts()

patients.diagnosis
H - Hit by Vehicle    166
Name: count, dtype: int64

In [14]:
# Grab the indexes of the rows that contain the string "Vehicle" in the patient.diagnosis column
diagnosis_column_vehicle = df[df['patients.diagnosis'].str.contains('Vehicle', regex=False, case=False, na=False)].index

### Reasons for Admission Column

In [15]:
df['patients.reasons_for_admission'].value_counts()

patients.reasons_for_admission
Cat attack                                          85
HBV                                                 50
Dog attack                                          37
Abandoned                                           34
Orphaned                                            31
                                                    ..
Hit the barn wall, unable to fly after 2 hours       1
Eyes swollen and crusted shut                        1
found down on side in yard, suspected leg injury     1
Injured leg, confirmed dog had cardinal in mouth     1
hit by car, DOA                                      1
Name: count, Length: 1812, dtype: int64

In [16]:
# Set up a regex pattern to match the string "vehicle" or "HBV" or "collision" in the patient.reasons_for_admission column
vehicle_collision_regex = "vehicle|HBV|collision"
# Find rows where the patients.ressons_for_admission column contains the string "vehicle" or "HBV" or "collision" and examine the results
df[df['patients.reasons_for_admission'].str.contains(vehicle_collision_regex, regex=True, case=False, na=False)]

,admissions.case_year,admissions.hash,admissions.id,exams.age,exams.age_unit,exams.attitude,exams.bcs,exams.body,exams.cardiopulmonary,exams.cns,...,people.notes,people.organization,people.phone,people.postal_code,people.subdivision,species.class,species.family,species.genus,species.order,species.species
6,2024,NaN,7,NaN,Adult,Obtunded,Reasonable,"OD susp ruptured, fluid and blood crusted over...",NaN,NaN,...,NaN,VCA,7.037512e+09,22314,VA,Mammalia,Sciuridae,Sciurus,Rodentia,carolinensis
10,2024,NaN,11,NaN,Adult,Obtunded,Good,lower jaw crushing injury and severely swollen...,NaN,NaN,...,NaN,NaN,4.349610e+09,22601,VA,Mammalia,Sciuridae,Sciurus,Rodentia,carolinensis
24,2024,NaN,25,NaN,Adult,Alert,Good,NaN,NaN,NaN,...,NaN,NaN,5.408126e+09,22640,VA,Aves,Cathartidae,Cathartes,Cathartiformes,aura
27,2024,NaN,28,NaN,Adult,Stuporous,NaN,very weak,extremely poor jugular fill,NaN,...,NaN,FCSO Deputy C. Amari,4.439550e+09,22630,VA,Aves,Strigidae,Bubo,Strigiformes,virginianus
31,2024,NaN,32,NaN,Adult,Stuporous,Thin,See Feathers/Fur/Skin,NaN,"Mentally inappropriate, appeared to be twitchi...",...,NaN,NaN,5.712748e+09,20180,VA,Mammalia,Procyonidae,Procyon,Carnivora,lotor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3272,2024,NaN,3271,NaN,Adult,Obtunded,Good,NaN,NaN,NaN,...,"Per HJ, finder (Richard) initially found BAOW ...",Loudoun Valley Raptors (Heather Jeweler),2.024121e+09,20165,VA,Aves,Strigidae,Strix,Strigiformes,varia
3274,2024,NaN,3273,NaN,Adult,Stuporous,Reasonable,"profuse bleeding from oral cavity, regurgitate...",NaN,NaN,...,NaN,NaN,5.408775e+09,20184,VA,Reptilia,Emydidae,Terrapene,Testudines,Carolina
3277,2024,NaN,3276,NaN,Adult,Obtunded,Good,OS large older appearing retinal tear along ve...,NaN,NaN,...,NaN,Loudoun Valley Raptor Center,7.034004e+09,NaN,VA,Aves,Strigidae,Megascops,Strigiformes,asio
3303,2024,NaN,3302,NaN,Juvenile,Depressed,Reasonable,NaN,"Open mouth breathing, moderatly dyspneic, wors...",NaN,...,NaN,NaN,5.406213e+09,22514,VA,Mammalia,Didelphidae,Didelphis,Didelphimorphia,virginiana
3308,2024,NaN,3307,NaN,Adult,Depressed,Reasonable,NaN,moderately increased respiratory effort,initially lateral,...,NaN,NaN,8.438227e+09,22642,VA,Mammalia,Sciuridae,Sciurus,Rodentia,carolinensis

In [17]:
# Grab the indexes of the rows that contain the string "Vehicle" in the patient.diagnosis column
reasonforadmission_column_vehicle = df[df['patients.reasons_for_admission'].str.contains(vehicle_collision_regex, regex=True, case=False, na=False)].index

### Unify hit by vechicle indexes

In [18]:
# Unify the indexes of the rows that we suspect are related to vehicle collisions
unified_indexes = keyword_column_hbv.union(diagnosis_column_vehicle).union(reasonforadmission_column_vehicle)

In [19]:
# Create a new DataFrame with only the rows that we suspect are related to vehicle collisions
df_vehicle_collisions = df.loc[unified_indexes]

In [27]:
df_vehicle_collisions.shape

(420, 95)

In [21]:
df_examime_location = df[['patients.disposition_lat',
       'patients.disposition_lng', 'patients.disposition_location',
       'patients.disposition_subdivision', 'patients.dispositioned_at',
       'patients.dispositioned_by', 'patients.found_at', 'patients.keywords',
       'patients.lat_found', 'patients.lng_found']]

In [22]:
# select rows from df_examiem_location_cols where patients.disposition_lat is not null
df_examime_location[df_examime_location['patients.disposition_lat'].notnull()]

,patients.disposition_lat,patients.disposition_lng,patients.disposition_location,patients.disposition_subdivision,patients.dispositioned_at,patients.dispositioned_by,patients.found_at,patients.keywords,patients.lat_found,patients.lng_found
56,31.390460,-92.669310,Boyce,VA,2024-01-23,JR,2024-01-22,mycotoxins,NaN,NaN
57,31.390460,-92.669310,Boyce,VA,2024-01-23,JR,2024-01-22,mycotoxins,NaN,NaN
58,31.390460,-92.669310,Boyce,VA,2024-01-23,JR,2024-01-22,mycotoxins,NaN,NaN
59,31.390460,-92.669310,Boyce,VA,2024-01-23,JR,2024-01-22,mycotoxins,NaN,NaN
60,31.390460,-92.669310,Boyce,VA,2024-01-23,JR,2024-01-22,mycotoxins,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
3073,39.048614,-78.060132,Boyce,VA,2024-09-01,JA,2024-08-30,B - Baby,NaN,NaN
3088,39.048614,-78.060132,Boyce,VA,2024-09-01,JA,2024-08-31,"B - Baby, fell from nest, orphan, renesting no...",NaN,NaN
3173,39.048614,-78.060132,Boyce,VA,NaN,NaN,2024-09-05,"B - Baby, suspect cat attack",NaN,NaN
3220,39.048614,-78.060132,Boyce,VA,2024-09-16,JA,2024-09-09,"B - Baby, suspect cat attack",NaN,NaN
3226,31.390460,-92.669310,Boyce,NaN,2024-09-10,JR,2024-09-10,"cat attack, B - Baby",NaN,NaN